version: "3.9"

services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shared-net

networks:
  shared-net:
    external: true
